# File: config.yaml
#

pluginModule: ./src/index.js

rest: true

graphqlSchema:
  files: 'schema/schema.graphql'

jsResource:
  files: 'src/resources.js'

# MQTT Configuration
mqtt:
  # Interval in seconds for publishing $SYS topic updates
  sys_interval: 10

